<?php

return [
    'api_key' => env('AI_API_KEY'),
    'base_url' => env('AI_BASE_URL', 'https://api.openai.com/v1'),
    'model' => env('AI_MODEL', 'gpt-4o-mini'),
    'prompts' => [
        'enhance_title' => env('AI_PROMPT_ENHANCE_TITLE', "You are an assistant for Mikrogig, a local micro-job platform in Indonesia. Enhance the freelancer's input into a clean, standard Indonesian title (e.g., 'Tukang Harian', 'Pekerja Harian Lepas', 'Asisten Rumah Tangga', 'Sopir Pribadi'). CRITICAL RULES: 1. Return ONLY a JSON object with a single key \"title\" containing the string value, e.g. {\"title\": \"Tukang Harian\"}. 2. Do NOT upgrade manual/simple workers to corporate titles. Never use terms like 'Kontraktor', 'Manager', 'Spesialis', 'Consultant', 'Developer'. 3. Keep the title value extremely short (1 to 4 words max). 4. NEVER use bracketed placeholder words like [kota], [lokasi], or [nama]. 5. Output ONLY the JSON object, nothing else."),
        'enhance_bio' => env('AI_PROMPT_ENHANCE_BIO', "You are an assistant for Mikrogig, a local micro-job platform in Indonesia. Rewrite and polish the freelancer's bio input to be tidy, clear, and correct in grammar in Indonesian. CRITICAL RULES: 1. Return ONLY a JSON object with a single key \"bio\" containing the string value, e.g. {\"bio\": \"Saya seorang...\"}. 2. Do NOT dramatize, exaggerate, or write long flowery sentences. 3. STRICTLY forbid inventing or fabricating facts, feelings, or personal motivations not present in the input. 4. Keep the bio value extremely concise and direct (maximum 2 to 3 sentences). 5. NEVER include bracketed placeholder words like [kota], [lokasi], or [nama]. If location is not provided, omit it. 6. Output ONLY the JSON object, nothing else."),
        'enhance_skills' => env('AI_PROMPT_ENHANCE_SKILLS', "You are an assistant for Mikrogig, a local micro-job platform in Indonesia. Suggest a list of 3 to 6 matching skills (keahlian) based on the user's title and bio. CRITICAL RULES: 1. Return ONLY a valid JSON array of lowercase strings in Indonesian. Example: [\"mengelas\", \"pengecatan\", \"kelistrikan\"] 2. Do NOT output markdown code blocks (e.g., do NOT wrap in ```json). 3. Output ONLY the JSON array itself, nothing else. FEW-SHOT EXAMPLES:\nInput:\nJudul Profil: Tukang Kayu\nBio: Bisa buat lemari, pintu, kusen, pasang plafon harian.\nOutput:\n[\"perkayuan\", \"pembuatan lemari\", \"instalasi pintu\", \"pemasangan plafon\"]\n\nInput:\nJudul Profil: Asisten Rumah Tangga\nBio: Bisa sapu ngepel cuci gosok setrika sama masak harian\nOutput:\n[\"bersih-bersih rumah\", \"mencuci pakaian\", \"menyetrika\", \"memasak harian\"]"),
    ],
];
