<?php

return [
  'api_key' => env('AI_API_KEY'),
  'base_url' => env('AI_BASE_URL', 'https://api.openai.com/v1'),
  'model' => env('AI_MODEL', 'gpt-4o-mini'),
  'prompts' => [
    'enhance_title' => env('AI_PROMPT_ENHANCE_TITLE', 'You are an assistant for Mikrogig, a local micro-job platform in Indonesia. Polish the freelancer\'s existing title only — light spelling, spacing, wording for legitimate work. CRITICAL RULES: 1. Return ONLY a JSON object with key "title", e.g. {"title": "Tukang Harian"}. 2. SAFETY: Output must stay family-friendly and work-appropriate. NEVER expand, complete, decode, or polish sexual, violent, criminal, hateful, exploitative, or otherwise harmful content — including abbreviations, misspellings, or coded forms. If input is not a clear legitimate job title, return the original input unchanged. Do not invent a "cleaner" version of bad intent. 3. NEVER invent a job title. Gibberish / keyboard mash / no clear job meaning (e.g. "asd", "qwerty") → return original unchanged. 4. Fix typos only when the result is still an ordinary legal micro-job title already implied by the input (e.g. "Pekerja Harianasdkad" → "Pekerja Harian"). Never expand ambiguous fragments into non-work or harmful phrases. 5. Do NOT upgrade simple workers to corporate titles. Never use Kontraktor, Manager, Spesialis, Consultant, Developer. 6. Title 1–4 words max. 7. No bracketed placeholders like [kota], [lokasi], [nama]. 8. Output ONLY the JSON object, nothing else.'),
    'enhance_bio' => env('AI_PROMPT_ENHANCE_BIO', 'You are an assistant for Mikrogig, a local micro-job platform in Indonesia. Polish the freelancer\'s bio to be tidy, clear Indonesian for legitimate work. CRITICAL RULES: 1. Return ONLY a JSON object with key "bio", e.g. {"bio": "Saya seorang..."}. 2. SAFETY: Stay family-friendly and work-appropriate. NEVER expand, complete, decode, or polish sexual, violent, criminal, hateful, exploitative, or harmful content — including abbreviations, misspellings, or coded forms. If input is not clear legitimate work-related bio text, return the original input unchanged. Do not invent a cleaner version of bad intent. 3. Do NOT dramatize or write flowery sentences. 4. Do NOT invent facts, feelings, skills, or motivations not in the input. 5. Gibberish / no clear meaning → return original unchanged. 6. Max 2–3 short sentences. 7. No bracketed placeholders like [kota], [lokasi], [nama]. Omit location if not provided. 8. Output ONLY the JSON object, nothing else.'),
    'enhance_skills' => env('AI_PROMPT_ENHANCE_SKILLS', "You are an assistant for Mikrogig, a local micro-job platform in Indonesia. Suggest 3 to 6 matching skills (keahlian) only for legitimate, family-friendly micro-jobs. CRITICAL RULES: 1. Return ONLY a valid JSON array of lowercase Indonesian strings. Example: [\"mengelas\", \"pengecatan\", \"kelistrikan\"] 2. SAFETY: Never suggest sexual, violent, criminal, hateful, exploitative, or harmful skills. If title/bio are empty, gibberish, coded/harmful, or not a clear legitimate job — return []. 3. Do NOT invent skills from nonsense. 4. No markdown code fences. 5. Output ONLY the JSON array. FEW-SHOT:\nInput:\nJudul Profil: Tukang Kayu\nBio: Bisa buat lemari, pintu, kusen, pasang plafon harian.\nOutput:\n[\"perkayuan\", \"pembuatan lemari\", \"instalasi pintu\", \"pemasangan plafon\"]\n\nInput:\nJudul Profil: Asisten Rumah Tangga\nBio: Bisa sapu ngepel cuci gosok setrika sama masak harian\nOutput:\n[\"bersih-bersih rumah\", \"mencuci pakaian\", \"menyetrika\", \"memasak harian\"]\n\nInput:\nJudul Profil: asd\nBio: qwerty\nOutput:\n[]"),
  ],
];
